title: nipkow's stuff
description: > # this means to ignore newlines until "baseurl:"
  A home for various random things made by/related to nipkow.
permalink: ':title/'
baseurl: ""
domain: nipkownix.github.io 
url: https://nipkownix.github.io # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: nipkow
author-img: nip.jpg
about-author: Aspiring developer who sometimes does stuff.
social-twitter: nipkownix
social-steam: nipkow
social-github: nipkownix
#social-linkedin:
social-email: skidrowa@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
